/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include<stm32f4xx.h>
void Led_Off(void);
void Led_On(void);


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void Ledon()
{
	GPIOD->ODR |= (BV(12));
	DelayMs(1000);

	GPIOD->ODR |= (BV(13));
	DelayMs(1000);

	GPIOD->ODR |= (BV(14));
	DelayMs(1000);

	GPIOD->ODR |= (BV(15));
	DelayMs(1000);

}

void Ledoff()
{
	GPIOD->ODR &=~ (BV(15));
	DelayMs(1000);

	GPIOD->ODR &=~ (BV(14));
	DelayMs(1000);

	GPIOD->ODR &=~ (BV(13));
	DelayMs(1000);

	GPIOD->ODR &=~ (BV(12));
	DelayMs(1000);

}

int main(void)
{
	// Led initalisation
	// Enable clock for GPIOD
	RCC->AHB1ENR |= BV(3);

	//SET GPIO D12,D13,D14,D15 as output
	GPIOD->MODER |= ( BV(24) | BV(26) | BV(28) | BV(30)     );
	GPIOD->MODER &= ~( BV(25) | BV(27) | BV(29) | BV(31)  );

	GPIOD->OTYPER |= ( BV(12) | BV(13) | BV(14) |BV(15));//open drain-1 and no push-pull-0

	GPIOD->OSPEEDR &= ~( BV(24) |  BV(25) | BV(26) | BV (27) | BV(28) | BV(29) | BV(30) | BV(31));

	//GPIOD->PUPDR &= ~( BV(24) |  BV(25) | BV(26) | BV (27) | BV(28) | BV(29) | BV(30) | BV(31));

		GPIOD->PUPDR |=( BV(24) | BV(26) | BV(28) | BV(30)     );
		GPIOD->PUPDR &= ~( BV(25) | BV(27) | BV(29) | BV(31)  );

			while(1)
			{

				Ledon();
				Ledoff();


			}
}
